# Generated by Django 6.0.7 on 2026-08-09 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_monthlybudget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
    ]
