# Generated by Django 6.0.7 on 2026-08-09 07:40

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_alter_expenses_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date_time',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2026, 8, 9, 7, 40, 41, 418223))]),
        ),
    ]
