# Generated by Django 6.0.7 on 2026-08-09 07:53

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expenses_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date_time',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(limit_value=django.utils.timezone.now)]),
        ),
    ]
