# Generated by Django 6.0.7 on 2026-08-09 08:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_alter_expenses_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date_time',
            field=models.DateTimeField(validators=[django.core.validators.MaxValueValidator(limit_value=datetime.datetime(2026, 8, 9, 8, 1, 34, 341960, tzinfo=datetime.timezone.utc))]),
        ),
    ]
