# Generated by Django 6.0.7 on 2026-08-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_expenses_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
