# Generated by Django 6.0.7 on 2026-08-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0010_alter_expenses_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensesRelatedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
